# Generated by Django 3.2.4 on 2021-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comentario')),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('carreraEspecialidad', models.TextField()),
                ('matricula', models.TextField()),
                ('telefono', models.TextField()),
                ('mensaje', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario contacto',
                'verbose_name_plural': 'Comentarios contactos',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='administrarempleados',
            name='apellidoMa',
            field=models.TextField(verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='administrarempleados',
            name='apellidoPa',
            field=models.TextField(verbose_name='Apellido Paterno'),
        ),
    ]
