# Generated by Django 3.2.4 on 2021-08-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20210828_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSolicitudes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombre', models.TextField()),
                ('apellidoPa', models.TextField(verbose_name='Apellido Paterno')),
                ('apellidoMa', models.TextField(verbose_name='Apellido Materno')),
                ('carreraEspecialidad', models.TextField()),
                ('matricula', models.TextField()),
                ('telefono', models.TextField()),
                ('turno', models.TextField()),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('material', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de solicitud',
                'verbose_name_plural': 'Registro de solicitudes',
                'ordering': ['-created'],
            },
        ),
    ]
